In [1]:
import tensorflow as tf 

a = tf.constant(5) 
b = tf.constant(2)
c = tf.constant(3)

d = tf.mul(a,b) 
e = tf.add(c,b) 

f = tf.sub(d,e) 

sess = tf.Session() 
outs = sess.run(f) 
sess.close() 

print "outs = {}".format(outs)

outs = 5


In [2]:
g = tf.Graph() 
print g

In [3]:
g = tf.Graph() 
print g

a = tf.constant(5)  
print a.graph 

print tf.get_default_graph() 

print a.graph is g
print a.graph is tf.get_default_graph()

False
True


In [4]:
g1 = tf.get_default_graph() 
g2 = tf.Graph() 

print g1 is tf.get_default_graph()

with g2.as_default(): 
    print g1 is tf.get_default_graph()

print g1 is tf.get_default_graph()

True
False
True


In [6]:
sess = tf.Session()
fetches = [a,b,c,d,e,f]
outs = sess.run(fetches) 
sess.close()
print "outs = {}".format(outs)

outs = [5, 2, 3, 10, 5, 5]


In [7]:
c = tf.constant(4.0) 
print c

Tensor("Const_4:0", shape=(), dtype=float32)


In [8]:
c = tf.constant(4.0, dtype='float64') 
print c
print c.dtype

Tensor("Const_5:0", shape=(), dtype=float64)
<dtype: 'float64'>


In [9]:
import numpy as np 

c = tf.constant([[1,2,3],[4,5,6]]) 
print "With Python List: {}".format(c.get_shape())

c = tf.constant(np.array([[1,2,3],[4,5,6]])) 
print "With Numpy array: {}".format(c.get_shape())

c = tf.constant([[[1,2,3], [4,5,6]], [[1,1,1], [2,2,2]]]) 
print "3d list: {}".format(c.get_shape())

With Python List: (2, 3)
With Numpy array: (2, 3)
3d list: (2, 2, 3)


In [11]:
c = tf.fill((3,2,2), 13) 
print c.get_shape()
sess = tf.Session() 
print sess.run(c) 
sess.close()

(3, 2, 2)
[[[13 13]
  [13 13]]

 [[13 13]
  [13 13]]

 [[13 13]
  [13 13]]]


In [12]:
c = tf.random_normal((3,3), mean=0.0, stddev=1.0) 
print c.get_shape()
sess = tf.Session() 
print sess.run(c) 
sess.close()

(3, 3)
[[ 0.30811131 -0.68112433 -1.09835541]
 [-0.75694317  0.91098231  0.30430576]
 [ 0.86925286  0.54640049  0.48557368]]


In [13]:
c = tf.linspace(0.0, 4.0, 5) 
print c.get_shape()
sess = tf.Session() 
print sess.run(c) 
sess.close()

(5,)
[ 0.  1.  2.  3.  4.]


In [14]:
import tensorflow as tf

with tf.Graph().as_default(): 
    x = tf.random_normal((5,10), mean=0.0, stddev=1.0) 
    w = tf.random_normal((10,1), mean=0.0, stddev=1.0) 
    b = tf.fill((5,1),-1.) 
    xw = tf.matmul(x,w) 

    xwb = xw + b 
    s = tf.sigmoid(xwb) 

    sess = tf.Session()             
    outs = sess.run(s)
    sess.close()

print "outs = {}".format(outs)

outs = [[ 0.03245385]
 [ 0.01749875]
 [ 0.02511816]
 [ 0.17290431]
 [ 0.37496576]]


In [15]:
with tf.Graph().as_default():
    c1 = tf.constant(4,dtype='float64',name='c') 
    c2 = tf.constant(4,dtype='int32',name='c') 
print c1.name
print c2.name

c:0
c_1:0


In [16]:
g1 = tf.Graph()
with g1.as_default():
    c1 = tf.constant(4,dtype='float64',name='c') 
print c1.name

g2 = tf.Graph()
with g2.as_default():
    c2 = tf.constant(4,dtype='int32',name='c') 

print c2.name

c:0
c:0


In [28]:
with tf.Graph().as_default():
    c1 = tf.constant(4,dtype='float64',name='c') 
    with tf.name_scope("2"):
        c2 = tf.constant(4,dtype='int32',name='c') 
        c3 = tf.constant(4,dtype='float64',name='c')

print c1.name
print c2.name
print c3.name

c:0 2/c:0 2/c_1:0


In [19]:
c = tf.constant(15, name='c') 
x = tf.Variable(c*5, name='x') 

init = tf.global_variables_initializer()
print x 

with tf.Session() as sess:
    sess.run(init)
    print sess.run(x)

Tensor("x_1/read:0", shape=(), dtype=int32)
75


In [29]:
import numpy as np
import tensorflow as tf

x_data = np.random.randn(5,10) 
w_data = np.random.randn(10,1) 

with tf.Graph().as_default():
    x = tf.placeholder('float32',shape=(5,10))
    w = tf.placeholder('float32',shape=(10,1))
    b = tf.fill((5,1),-1.) 
    xw = tf.matmul(x,w)

    xwb = xw + b
    s = tf.reduce_max(xwb)
    with tf.Session() as sess:
        outs = sess.run(s,feed_dict={x: x_data,w: w_data}) 

print "outs = {}".format(outs)

outs = -1.06374239922


In [30]:
x = tf.placeholder('float32',shape=None)
w = tf.Variable([0.1,0.2,0.3],dtype='float32')
b = tf.Variable(0.5,dtype='float32')

y_pred = x*w + b

In [31]:
y_true = tf.placeholder('float32',shape=None)
loss = tf.reduce_mean(tf.square(y_true-y_pred))

In [32]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.5)
train = optimizer.minimize(loss)

In [33]:
import numpy as np

# Create toy dataset 
x_data = np.random.randn(2000,3)
w_real = [0.3,0.5,0.1]
b_real = -0.2

noise = np.random.randn(2000,1)*0.1
y_data = x_data*w_real+ b_real + noise

In [27]:
import tensorflow as tf

NUM_STEPS = 30

with tf.Graph().as_default():
    x = tf.placeholder('float32',shape=None)
    y_true = tf.placeholder('float32',shape=None)

    w = tf.Variable([0,0,0],dtype='float32')
    b = tf.Variable(0,dtype='float32')

    y_pred = x*w + b
    loss = tf.reduce_mean(tf.square(y_true-y_pred))

    optimizer = tf.train.GradientDescentOptimizer(0.5)
    train = optimizer.minimize(loss)
    
    init = tf.global_variables_initializer()
    
    with tf.Session() as sess:
        sess.run(init)      
        for step in range(NUM_STEPS):
            sess.run(train,{x: x_data, y_true: y_data})
            if step % 5 == 0:
                print step, sess.run([w,b])

0 [array([ 0.1008704 ,  0.15766016,  0.0367507 ], dtype=float32), -0.19526303]
5 [array([ 0.27653056,  0.44794244,  0.0957488 ], dtype=float32), -0.1969059]
10 [array([ 0.29882082,  0.49121752,  0.10322051], dtype=float32), -0.19713061]
15 [array([ 0.30164942,  0.49766889,  0.10416666], dtype=float32), -0.19716097]
20 [array([ 0.30200836,  0.49863064,  0.10428645], dtype=float32), -0.1971651]
25 [array([ 0.30205393,  0.49877402,  0.10430161], dtype=float32), -0.19716567]
